### PR TITLE
C/C++ Variant

### PR DESCRIPTION
**Pull request by hhenry01**
Added files and instructions to do the quiz in C/C++.

@patrick-5546 I don't know how to add this to the Github workflow. If it helps, this is the output of a successful run:
```
$ make
g++ *.cpp cutest/CuTest.c -Wall -o test_standard_calc.o
$ ./test_standard_calc.o
..

OK (2 tests)
```

### CODE REVIEW

**Comment by patrick-5546** [comment]
Would it be possible to put all the c/c++ stuff in a subdirectory? We can do the same with the python stuff.

Edit: I've done this already

**Comment by patrick-5546** [comment]
Here is the default make c/c++ make action

```yml

name: C/C++ CI
​
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
​
jobs:
  build:
​
    runs-on: ubuntu-latest
​
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
```

Is running `make` sufficient, or should I also run `make check` and `make distcheck` afterwards?

I'm also guessing that running `./configure` first is not required

**Comment by patrick-5546** [comment]
One more thing. Is there a way that applicants can complete the quiz without using Git? I want to give them the option to download the ZIP file of the repo

**Comment by patrick-5546** [comment]
Can you take a look at my changes? 

One question I had: since the c/c++ CI is just running `make`, what happens if someone wants to use another unit test framework? Maybe we should add a sentence about changing the makefile in the README

Once you reviewed my changes, can you merge this into master and run through the instructions? We should create a private repository with sample answers. Thanks

**Review by patrick-5546 — APPROVED** [review]

**Comment by hhenry01** [comment]
> Can you take a look at my changes?
> 
> One question I had: since the c/c++ CI is just running `make`, what happens if someone wants to use another unit test framework? Maybe we should add a sentence about changing the makefile in the README
> 
> Once you reviewed my changes, can you merge this into master and run through the instructions? We should create a private repository with sample answers. Thanks

If someone wants to use a different unit test framework, it might not be as simple as changing the Makefile. For example, GoogleTest uses CMake. So I don't think I can write a universal set of instructions for changing the unit test framework.

**Comment by hhenry01** [comment]
I figured out how to make the CI check if running `./test_standard_calc.o` fails.

**Pull request merged**
